apiVersion: v1
kind: ConfigMap
metadata:
  name: run-hoban-run-firebase-deploy
  labels:
    app.kubernetes.io/name: run-hoban-run
data:
  sourceRepo: https://github.com/yeominsoo/run-hoban-run.git
  sourceRevision: master
  sourceSha: "9a4503b65737d5132e65b6bc6b5365ba39f019e4"
  firebaseProject: hoban-lakepark-ab19
  image: ghcr.io/yeominsoo/run-hoban-run:firebase
