apiVersion: v1
kind: ConfigMap
metadata:
  name: run-hoban-run-firebase-deploy
  labels:
    app.kubernetes.io/name: run-hoban-run
data:
  sourceRepo: https://github.com/yeominsoo/run-hoban-run.git
  sourceRevision: master
  sourceSha: "e14ef70001d318bb53b98e9c99de8f1fd373c406"
  firebaseProject: hoban-lakepark-ab19
  image: ghcr.io/yeominsoo/run-hoban-run:firebase
