apiVersion: v1
kind: ConfigMap
metadata:
  name: run-hoban-run-firebase-deploy
  labels:
    app.kubernetes.io/name: run-hoban-run
data:
  sourceRepo: https://github.com/yeominsoo/run-hoban-run.git
  sourceRevision: master
  sourceSha: "ffb806159b91505b9e87cac52fc35ca5522d1f12"
  firebaseProject: hoban-lakepark-ab19
  image: ghcr.io/yeominsoo/run-hoban-run:firebase
