apiVersion: v1
kind: Service
metadata:
  name: run-hoban-run
  labels:
    app.kubernetes.io/name: run-hoban-run
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: run-hoban-run
  ports:
    - name: http
      port: 15173
      targetPort: http
