apiVersion: v1
kind: Service
metadata:
  name: run-hoban-run-ws
  labels:
    app.kubernetes.io/name: run-hoban-run-ws
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: run-hoban-run-ws
  ports:
    - name: ws
      port: 8787
      targetPort: ws
      nodePort: 30080
