services:
  frontend:
    build: .
    container_name: run-hoban-run-frontend
    ports:
      - "15173:15173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev -- --host 0.0.0.0 --port 15173 --strictPort
