server {
    listen 30080 ssl;
    server_name toris-arcade.duckdns.org 58.228.188.17 _;

    ssl_certificate     /etc/letsencrypt/live/toris-arcade.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/toris-arcade.duckdns.org/privkey.pem;

    location /ranking {
        proxy_pass http://127.0.0.1:30081/ranking;
    }

    location /healthz {
        proxy_pass http://127.0.0.1:30081/healthz;
    }

    location /rps {
        proxy_pass http://127.0.0.1:30081/rps;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
    }

    location /liar {
        proxy_pass http://127.0.0.1:30081/liar;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
    }
}
