namespace: run-hoban-run

resources:
- namespace.yaml
- ../../base

images:
- name: ghcr.io/yeominsoo/run-hoban-run
  newName: ghcr.io/yeominsoo/run-hoban-run
  newTag: 01e4b5c8aace11bf5b9b723029087463d5bc4055
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
