namespace: run-hoban-run

resources:
- namespace.yaml
- ../../base

images:
- name: ghcr.io/yeominsoo/run-hoban-run
  newName: ghcr.io/yeominsoo/run-hoban-run
  newTag: c2d79e24d440b44cfa30ece14ff2e83ef71e9de0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
